import sqlite3

def populate_database():
    conn = sqlite3.connect('music.db')
    cursor = conn.cursor()

    songs = [
        
        ('Blinding Lights', 'The Weeknd', 'Pop', 171, 0.8),
        ('Save Your Tears', 'The Weeknd', 'Pop', 118, 0.7),
        ('Starboy', 'The Weeknd', 'Pop', 186, 0.9),
        ('Midnight City', 'M83', 'Electronic', 105, 0.7),
        ('Nightcall', 'Kavinsky', 'Electronic', 91, 0.5),
        ('After Dark', 'Mr.Kitty', 'Electronic', 140, 0.6),
        ('Resonance', 'Home', 'Electronic', 170, 0.4),
        ('Levitating', 'Dua Lipa', 'Pop', 103, 0.8),
        ('Physical', 'Dua Lipa', 'Pop', 147, 0.9),
        ('As It Was', 'Harry Styles', 'Pop', 174, 0.7),
        ('Style', 'Taylor Swift', 'Pop', 95, 0.6),
        ('Blind', 'Hercules & Love Affair', 'Dance', 118, 0.8),
        ('True Survivor', 'David Hasselhoff', 'Synthwave', 110, 0.9),
        ('Turbo Killer', 'Carpenter Brut', 'Synthwave', 160, 0.95),
        ('Do I Wanna Know?', 'Arctic Monkeys', 'Rock', 85, 0.5),
        ('R U Mine?', 'Arctic Monkeys', 'Rock', 97, 0.9),
        ('The Less I Know The Better', 'Tame Impala', 'Rock', 117, 0.6),
        ('Elephant', 'Tame Impala', 'Rock', 124, 0.8),
        ('Seven Nation Army', 'The White Stripes', 'Rock', 123, 0.7),
        ('Radioactive', 'Imagine Dragons', 'Rock', 136, 0.8),
        ('Smells Like Teen Spirit', 'Nirvana', 'Grunge', 117, 0.9),
        ('Creep', 'Radiohead', 'Alternative', 92, 0.4),
        ('Starlight', 'Muse', 'Rock', 121, 0.8),
        ('Sweater Weather', 'The Neighbourhood', 'Indie', 124, 0.4),
        ('Feel Good Inc', 'Gorillaz', 'Alternative', 139, 0.7),
        ('Californication', 'Red Hot Chili Peppers', 'Rock', 96, 0.6),
        ('In the End', 'Linkin Park', 'Nu-Metal', 105, 0.8),
        ('Bring Me To Life', 'Evanescence', 'Rock', 190, 0.8),
        ('Sweet Child O Mine', 'Guns N Roses', 'Rock', 125, 0.9),
        ('One More Time', 'Daft Punk', 'Electronic', 123, 0.7),
        ('Instant Crush', 'Daft Punk', 'Electronic', 110, 0.6),
        ('Titanium', 'David Guetta', 'Dance', 126, 0.8),
        ('Wake Me Up', 'Avicii', 'Dance', 124, 0.8),
        ('Clarity', 'Zedd', 'Dance', 128, 0.7),
        ('Strobe', 'deadmau5', 'Electronic', 128, 0.5),
        ('Animals', 'Martin Garrix', 'Electronic', 128, 0.8),
        ('Scary Monsters and Nice Sprites', 'Skrillex', 'Dubstep', 140, 0.9),
        ('Lean On', 'Major Lazer', 'Electronic', 98, 0.8),
        ('Faded', 'Alan Walker', 'Electronic', 90, 0.6),
        ('Sandstorm', 'Darude', 'Trance', 136, 0.9),
        ('Levels', 'Avicii', 'House', 126, 0.8),
        ('Sicko Mode', 'Travis Scott', 'Hip-Hop', 155, 0.7),
        ('Humble', 'Kendrick Lamar', 'Hip-Hop', 150, 0.7),
        ('Godzilla', 'Eminem', 'Hip-Hop', 166, 0.8),
        ('Mask Off', 'Future', 'Hip-Hop', 150, 0.4),
        ('Gods Plan', 'Drake', 'Hip-Hop', 77, 0.4),
        ('Praise The Lord', 'A$AP Rocky', 'Hip-Hop', 80, 0.6),
        ('Sunflower', 'Post Malone', 'Hip-Hop', 90, 0.5),
        ('Circles', 'Post Malone', 'Pop', 120, 0.6),
        ('Lucid Dreams', 'Juice WRLD', 'Hip-Hop', 84, 0.6),
        ('Old Town Road', 'Lil Nas X', 'Country Trap', 136, 0.5),
        ('Lose Yourself', 'Eminem', 'Hip-Hop', 171, 0.8),
        ('California Love', '2Pac', 'Hip-Hop', 92, 0.8),
        ('Lofi Rain', 'Lofi Girl', 'Lo-Fi', 80, 0.2),
        ('Coffee Breath', 'Neotic', 'Lo-Fi', 85, 0.1),
        ('Snowman', 'WYS', 'Lo-Fi', 75, 0.2),
        ('Death Bed', 'Powfu', 'Lo-Fi', 144, 0.4),
        ('Sunset Lover', 'Petit Biscuit', 'Electronic', 91, 0.4),
        ('Weightless', 'Marconi Union', 'Ambient', 60, 0.1),
        ('Clair de Lune', 'Debussy', 'Classical', 65, 0.1),
        ('River Flows in You', 'Yiruma', 'Classical', 72, 0.2),
        ('Gymnopedie No.1', 'Erik Satie', 'Classical', 74, 0.1),
        ('Moonlight Sonata', 'Beethoven', 'Classical', 60, 0.1),
        ('Luna', 'Carla\'s Dreams', 'Pop', 120, 0.6),
        ('Sub Pielea Mea', 'Carla\'s Dreams', 'Pop', 125, 0.7),
        ('Pana la sange', 'Carla\'s Dreams', 'Pop', 130, 0.6),
        ('Inapoi la om', 'Vița de Vie', 'Rock', 110, 0.7),
        ('Basul si cu toba mare', 'Vița de Vie', 'Rock', 128, 0.9),
        ('Perfect', 'Vama', 'Pop-Rock', 115, 0.7),
        ('Epilog', 'Vama Veche', 'Ballad', 80, 0.3),
        ('Havana', 'Camila Cabello', 'Pop', 105, 0.5),
        ('Shape of You', 'Ed Sheeran', 'Pop', 96, 0.65),
        ('Bad Guy', 'Billie Eilish', 'Pop', 135, 0.4),
        ('Rolling in the Deep', 'Adele', 'Soul', 105, 0.8),
        ('Uptown Funk', 'Bruno Mars', 'Funk', 115, 0.9),
        ('Shake It Off', 'Taylor Swift', 'Pop', 160, 0.8),
        ('Cheap Thrills', 'Sia', 'Pop', 90, 0.7),
        ('Thank U, Next', 'Ariana Grande', 'Pop', 107, 0.6),
        ('Sorry', 'Justin Bieber', 'Pop', 100, 0.75),
        ('Firework', 'Katy Perry', 'Pop', 124, 0.8),
        ('Flowers', 'Miley Cyrus', 'Pop', 118, 0.7),
        ('Stay', 'The Kid LAROI', 'Pop', 170, 0.8),
        ('Despacito', 'Luis Fonsi', 'Reggaeton', 89, 0.8),
        ('Senorita', 'Shawn Mendes', 'Pop', 117, 0.5),
        ('Titanium', 'David Guetta', 'Dance', 126, 0.8),
        ('Poker Face', 'Lady Gaga', 'Pop', 119, 0.8),
        ('Single Ladies', 'Beyonce', 'Pop', 97, 0.75),
        ('Diamonds', 'Rihanna', 'Pop', 92, 0.6),
        ('Watermelon Sugar', 'Harry Styles', 'Pop', 95, 0.8),
        ('Drivers License', 'Olivia Rodrigo', 'Pop', 144, 0.4),
        ('Bohemian Rhapsody', 'Queen', 'Rock', 72, 0.4),
        ('Another One Bites the Dust', 'Queen', 'Rock', 110, 0.5),
        ('Hotel California', 'Eagles', 'Rock', 75, 0.5),
        ('Thunderstruck', 'AC/DC', 'Rock', 134, 0.9),
        ('Back in Black', 'AC/DC', 'Rock', 91, 0.85),
        ('Livin On A Prayer', 'Bon Jovi', 'Rock', 123, 0.8),
        ('Every Breath You Take', 'The Police', 'Rock', 117, 0.4),
        ('Wonderwall', 'Oasis', 'Britpop', 174, 0.4),
        ('Losing My Religion', 'R.E.M.', 'Alternative', 125, 0.8),
        ('Africa', 'Toto', 'Rock', 93, 0.4),
        ('Eye of the Tiger', 'Survivor', 'Rock', 109, 0.6),
        ('Billie Jean', 'Michael Jackson', 'Pop', 117, 0.7),
        ('Beat It', 'Michael Jackson', 'Pop', 138, 0.9),
        ('Smells Like Teen Spirit', 'Nirvana', 'Grunge', 117, 0.9),
        ('Come As You Are', 'Nirvana', 'Grunge', 120, 0.6),
        ('Under the Bridge', 'Red Hot Chili Peppers', 'Rock', 85, 0.4),
        ('Purple Rain', 'Prince', 'Pop', 113, 0.5),
        ('Enter Sandman', 'Metallica', 'Metal', 123, 0.8),
        ('Nothing Else Matters', 'Metallica', 'Metal', 142, 0.35),
        ('Wish You Were Here', 'Pink Floyd', 'Rock', 60, 0.25),
        ('The Next Episode', 'Dr. Dre', 'Hip-Hop', 95, 0.8),
        ('In Da Club', '50 Cent', 'Hip-Hop', 90, 0.7),
        ('Gangstas Paradise', 'Coolio', 'Hip-Hop', 80, 0.5),
        ('Godzilla', 'Eminem', 'Hip-Hop', 166, 0.8),
        ('Stronger', 'Kanye West', 'Hip-Hop', 104, 0.8),
        ('Empire State of Mind', 'Jay-Z', 'Hip-Hop', 173, 0.8),
        ('Hotline Bling', 'Drake', 'R&B', 135, 0.4),
        ('Starboy', 'The Weeknd', 'Pop', 186, 0.9),
        ('No Guidance', 'Chris Brown', 'R&B', 93, 0.4),
        ('Yeah!', 'Usher', 'R&B', 105, 0.8),
        ('C.R.E.A.M.', 'Wu-Tang Clan', 'Hip-Hop', 90, 0.6),
        ('Juicy', 'The Notorious B.I.G.', 'Hip-Hop', 96, 0.7),
        ('Nuthin but a G Thang', 'Dr. Dre', 'Hip-Hop', 95, 0.7),
        ('Paper Planes', 'M.I.A.', 'Hip-Hop', 172, 0.6),
        ('Gold Digger', 'Kanye West', 'Hip-Hop', 93, 0.7),
        ('Toxic', 'Britney Spears', 'Pop', 143, 0.8),
        ('Mr. Brightside', 'The Killers', 'Indie', 148, 0.9),
        ('Seven Nation Army', 'The White Stripes', 'Rock', 123, 0.7),
        ('Hey Ya!', 'Outkast', 'Hip-Hop', 160, 0.9),
        ('Complicated', 'Avril Lavigne', 'Pop', 78, 0.7),
        ('Bring Me To Life', 'Evanescence', 'Rock', 190, 0.8),
        ('Numb', 'Linkin Park', 'Rock', 110, 0.8),
        ('Sugar We Are Goin Down', 'Fall Out Boy', 'Pop-Punk', 162, 0.9),
        ('Hollaback Girl', 'Gwen Stefani', 'Pop', 110, 0.9),
        ('Sk8er Boi', 'Avril Lavigne', 'Pop-Punk', 150, 0.9),
        ('Yellow', 'Coldplay', 'Rock', 173, 0.4),
        ('Clocks', 'Coldplay', 'Rock', 131, 0.7),
        ('Lean On', 'Major Lazer', 'Dance', 98, 0.8),
        ('Levels', 'Avicii', 'House', 126, 0.8),
        ('Wake Me Up', 'Avicii', 'Dance', 124, 0.8),
        ('One More Time', 'Daft Punk', 'Electronic', 123, 0.7),
        ('Get Lucky', 'Daft Punk', 'Funk', 116, 0.8),
        ('Scary Monsters and Nice Sprites', 'Skrillex', 'Dubstep', 140, 0.9),
        ('Don’t You Worry Child', 'Swedish House Mafia', 'House', 129, 0.8),
        ('Heroes', 'Alesso', 'House', 126, 0.7),
        ('Animals', 'Martin Garrix', 'Electronic', 128, 0.8),
        ('Clarity', 'Zedd', 'Dance', 128, 0.7),
        ('Lullaby', 'R3HAB', 'Dance', 105, 0.7),
        ('Alone', 'Marshmello', 'Dance', 142, 0.7),
        ('Sweater Weather', 'The Neighbourhood', 'Indie', 124, 0.4),
        ('Take Me To Church', 'Hozier', 'Indie', 129, 0.6),
        ('Pompeii', 'Bastille', 'Indie', 127, 0.7),
        ('Riptide', 'Vance Joy', 'Indie', 102, 0.7),
        ('Ho Hey', 'The Lumineers', 'Folk', 80, 0.4),
        ('Budapest', 'George Ezra', 'Folk', 128, 0.4),
        ('Renegades', 'X Ambassadors', 'Indie', 90, 0.5),
        ('Heat Waves', 'Glass Animals', 'Indie', 81, 0.5),
        ('Suna Periculos', 'A.S.I.A', 'Pop', 128, 0.8),
        ('Dragostea Din Tei', 'O-Zone', 'Dance', 130, 0.9),
        ('Vrei sa pleci', 'O-Zone', 'Dance', 130, 0.85),
        ('Fericirea are chipul tau', 'Mihaela Runceanu', 'Classic', 100, 0.4),
        ('Buna seara, iubito', 'Loredana Groza', 'Classic', 85, 0.5),
        ('Zambetul de pe fata', 'B.U.G. Mafia', 'Hip-Hop', 92, 0.7),
        ('Poveste fara sfarsit', 'B.U.G. Mafia', 'Hip-Hop', 90, 0.75),
        ('Ridica-ma la cer', 'B.U.G. Mafia', 'Hip-Hop', 94, 0.8),
        ('Strada mea', 'La Familia', 'Hip-Hop', 90, 0.7),
        ('In lipsa mea', 'Smiley', 'Pop', 95, 0.6),
        ('Oficial imi merge bine', 'Simplu', 'Pop', 110, 0.8),
        ('Lumea e a mea', 'B.U.G. Mafia', 'Hip-Hop', 95, 0.8)
    ]

    try:
        cursor.executemany('''
            INSERT OR REPLACE INTO Songs (Title, Artist, Genre, Tempo, Energy) 
            VALUES (?, ?, ?, ?, ?)
        ''', songs)
        
        conn.commit()
        print(f"Succes! Baza de date a fost populata")
    except Exception as e:
        print(f"Eroare la populare: {e}")
    finally:
        conn.close()

if __name__ == "__main__":
    populate_database()